/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({

    requires: [
        'Arbela.view.datasources.Dummy',
        'Arbela.view.datasources.Sales',
        'Arbela.view.common.CalculatedField'
    ],
    views: [
        'MyViewport',
        'db.tb.Toolbar',
        'ws.Toolbar',
        'ws.Workspace',
        'db.main.Dashboard',
        'ds.List',
        'common.NewWindow',
        'common.WindowToolbar',
        'db.card.NewCard',
        'api.Card',
        'blades.Dummy',
        'blades.TotalSales',
        'blades.WebsiteTraffics',
        'blades.SupportTickets',
        'blades.BooksList',
        'blades.InventoryChart'
    ],
    name: 'Arbela',

    launch: function() {
        Ext.create('Arbela.view.MyViewport');
    }

});
