/*
 * File: app/view/db/ToolbarViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Arbela.view.db.ToolbarViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dbtoolbar',

    onAddCardBtnClick: function(button, e, eOpts) {
        var v = this.getView();
        v.fireEvent('addcard', v, button, e, eOpts);
    },

    onCloneBtnClick: function(button, e, eOpts) {
        var v = this.getView();
        v.fireEvent('clonedashboard', v, button, e, eOpts);
    }

});
