/*
 * File: app/view/ws/Toolbar.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Arbela.view.ws.Toolbar', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.wstoolbar',

    requires: [
        'Arbela.view.ws.ToolbarViewModel',
        'Ext.form.Label',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'wstoolbar'
    },

    layout: {
        type: 'hbox',
        pack: 'end'
    },
    items: [
        {
            xtype: 'label',
            text: 'ARBELA'
        },
        {
            xtype: 'label',
            flex: 1
        },
        {
            xtype: 'button',
            text: 'Notifications'
        },
        {
            xtype: 'button',
            text: 'Data Sources'
        }
    ]

});