/*
 * File: app/view/ws/Workspace.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Arbela.view.ws.Workspace', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.wsworkspace',

    requires: [
        'Arbela.view.ws.Toolbar',
        'Arbela.view.ds.List',
        'Arbela.view.db.main.Dashboard',
        'Ext.toolbar.Toolbar',
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    layout: 'border',
    header: false,
    title: 'My Panel',

    dockedItems: [
        {
            xtype: 'wstoolbar',
            dock: 'top'
        }
    ],
    items: [
        {
            xtype: 'dslist',
            collapsed: true,
            collapsible: true,
            titleCollapse: true,
            region: 'east',
            split: true
        },
        {
            xtype: 'tabpanel',
            region: 'center',
            tabPosition: 'left',
            tabRotation: 0,
            items: [
                {
                    xtype: 'dbdashboard'
                },
                {
                    xtype: 'panel',
                    title: 'Add'
                }
            ]
        }
    ]

});