/*
 * File: app/view/common/NewWindow.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Arbela.view.common.NewWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.commonnewwindow',

    requires: [
        'Arbela.view.common.NewWindowViewModel',
        'Arbela.view.common.NewWindowViewController',
        'Arbela.view.common.WindowToolbar',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar'
    ],

    config: {
        autoGrow: true,
        typeData: [],
        values: {}
    },
    
    dirtyMsg: 'There are unsaved changes. Do you want to ignore them and continue?',

    controller: 'commonnewwindow',
    publishes: [
        'typeData'
    ],
    reference: 'newwindow',

    viewModel: {
        type: 'commonnewwindow'
    },
    autoShow: true,
    height: 170,
    width: 400,
    bodyPadding: 10,
    layout: 'fit',
    title: 'New',

    modal: true,

    items: {
        xtype: 'form',
        items: [{
                xtype: 'textfield',
                fieldLabel: 'Name',
                name: 'name'
            }, {
                xtype: 'combobox',
                fieldLabel: 'Type',
                name: 'type',
                emptyText: 'Select a type',
                queryMode: 'local',
                valueField: 'klass',
                displayField: 'name',
                triggerAction: 'all',
                bind: {
                    store: '{types}'
                },
                listeners: {
                    select: 'onComboboxSelect',
                    change: 'onComboboxChange'
                }
            }
        ]
    },

    dockedItems: [
        {
            xtype: 'commonwindowtoolbar',
            dock: 'bottom',
            listeners: {
                click: 'onToolbarBtnClick'
            }
        }
    ],

    updateValues: function(newValues) {
        console.log('Appying: ', newValues);
        this.down('form').loadRecord(newValues);
    },

    setTypeData: function(typeData) {
        this.getViewModel().getStore('types').setData(typeData);
    }

});